travis:
  secure:
    BINSTAR_TOKEN: hl0Yy12kIoVVQwWcNGpV17fbQz0t+RH3WA00CjTopdhb00UdXndcXjcl5xEztvlBeuPU4w6O77hk0QJ6TXPQ0I/xkcE/l6oRTT6VB/f3B4As3s4LB5+lWpcEj2osiftxBCS7TK3HRmM5Y/Qh55+xNmYl536rjPjlYeWMgvAhONqxdTG9p2m5bXmtxU+YAnv7Hmcmzlw37zh/XUm+epmJV8TiNyG567u/touPxAEf2GGHC23ZeaiG6W3VvUJ9N7tzIJkZQR/hCEZOr3FImJtSnpE2auj9HbP/6DA2Cb/bU4gAjfLt7D+eRqJP7sTfqUjiqt0kOTqa2z4NQr+GP1598Y/AiNi6yMH58OGZ+6V3pQY0trc/kRS/aavbO3P/ZUsRviZAaaOlw9k84LynW0Ychwjj2pVl92FpxzuP17QI6aOr21Ut8a/hnEMura0eVvtKEs4keXQz5u03KcMEjcQchis6zfnh7U5utZiV5neUV10KrwLpsGuRKa5QnNymFErsf4bBnupkMRW4lH1SICMxsZo5DvJtkQXYyQEsnAB6TxfEmm+GLqcMQcHoMRipxTwfbsfrZJg0XGAqLdFQBVJxvLVtu6LBfEC20MAW2nvFmQU5BLVCbSB2fdQPpcL8S5a55z7I7Nk9+fgykRmolyYkBN45MvEfcbKyWkwOHjhwotM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
